apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  namespaces: jenkins
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 10Gi